actor_mode: hybrid
algorithm: blender
anneal_lr: true
batch_size: 768
blend_ent_coef: 0.01
blend_function: softmax
blender_learning_rate: 0.00025
blender_mode: logic
capture_video: false
clip_coef: 0.1
clip_vloss: true
cuda: true
ent_coef: 0.01
env_id: Seaquest-v4
env_name: riverraid
exp_name: train_blenderl
gae_lambda: 0.95
gamma: 0.99
joint_training: true
learning_rate: 0.00025
logic_learning_rate: 0.00025
max_grad_norm: 0.5
minibatch_size: 192
norm_adv: true
num_envs: 6
num_iterations: 78125
num_minibatches: 4
num_steps: 128
pretrained: false
reasoner: nsfr
recover: false
rules: default
save_steps: 500000
seed: 0
target_kl: null
torch_deterministic: true
total_timesteps: 60000000
track: false
update_epochs: 10
vf_coef: 0.5
wandb_entity: null
wandb_project_name: blendeRL
